### ISSUE TITLE
Collecting the information about citations

### ISSUE THREAD

**Issue by EliseAld** [scRNA-tools/scRNA-tools#152]
Hi there,
Thanks for the great website ! It is a useful resource. I wonder if you could help me extract the number of citations per published tool ? I am struggling trying to do it by myself.
Many thanks!
Cheers,
Elise

**Comment by lazappi** [comment]
Hi @EliseAld

Thanks for using the website! 🎉 The easiest way to download the citation information is probably by going to the table page and clicking the download button on the top right above the table.

![Screen Shot 2021-06-25 at 15 06 14](https://user-images.githubusercontent.com/6869320/123429320-1ad05080-d5c7-11eb-8d21-23af6df32710.png)

If there is other information you would like you can add/remove columns using the columns button (just to the left of download, looks like a grid of squares). Any sorting/filtering you do should also affect what you get in the download.

Hope that helps!

**Comment by EliseAld** [comment]
Hello @lazappi,
Oh mist, that was an easy one but I was focused on the tools page.
Thanks for the help and the quick answer!
