### ISSUE TITLE
Layout issues

### ISSUE THREAD

**Issue by Hrovatin** [scRNA-tools/scRNA-tools#161]
On the webpage when scrolling the layout breaks and text starts to overlap
<img width="1404" alt="image" src="https://user-images.githubusercontent.com/47607471/127745009-dc89ddb8-6c80-4fc5-a0cb-6933a4141b1a.png">

**Comment by Hrovatin** [comment]
Also, missing scrollbar on the bottom:
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/47607471/127745135-bdab9d7a-d201-4779-aba4-ca617ff25f66.png">

**Comment by lazappi** [comment]
Huh, that's weird. I haven't seen that before, thanks for reporting 🎉!

Which browser are you using?

**Comment by Hrovatin** [comment]
Firefox

**Comment by lazappi** [comment]
Hmmm... I just installed Firefox to check and seems fine here. Do you have and plugins installed that might be an issue?

**Comment by Hrovatin** [comment]
Not sure. But I do not think so.

**Comment by lazappi** [comment]
I'm going to close this but feel free to reopen if it's still happening.
