### ISSUE TITLE
Add data single cell modalities as categories

### ISSUE THREAD

**Issue by chris-rands** [scRNA-tools/scRNA-tools#184]
Thanks for this great resource! Would it be possible to add the single cell modality as a category or tag to enable further filtering of tools? E.g. scRNAseq, snRNAseq, scATACseq/multiome, CITE-seq, scVDJ etc.

**Comment by lazappi** [comment]
Hi @chris-rands. Thanks for the kind words! The database is limited to tools that can be used to analyse scRNA-seq data so tagging that probably isn't useful. There would definitely be scope for a "Multiomics" category for tools that can incorporate other modalities (currently these are covered by the "Integration" category but that also includes things like batch-correction methods).

The bottleneck for adding new categories is re-tagging everything that is currently in the database, once there is a list it's relatively straightforward. Is there any chance you would be interested in helping out with that?

**Comment by chris-rands** [comment]
I can see there is quite a bit of manual effort involved to re-tagging, so it might require a community effort. What I noticed in the list is cellranger (all 10X modalities), scirpy and conga (both RNA + VDJ), and CITEseqCount (CITE-seq; RNA + protein). The popular downstream tools like seurat/scanpy/scvi-tools support various modalities too. Obviously this is not systematic

**Comment by lazappi** [comment]
I'm going to close this issue but I have added Multiomics to our suggested new categories list https://github.com/scRNA-tools/scRNA-tools/issues/90

**Comment by zrq0123** [comment]
您的邮件已收到
