### ISSUE TITLE
Request:  Add date information to table export

### ISSUE THREAD

**Issue by ColeWunderlich** [scRNA-tools/scRNA-tools#78]
It would be nice to have the `date added` and `date updated` fields added to the table export.  This would allow people to normalize citation count by date added in order to get a more apples-to-apples comparison of tool popularity.

Also, I don't know if you have data on when the pre-prints/papers supporting each tool were published, but that would be nice to include in both the table and tool views if available.

**Comment by lazappi** [comment]
Hi

Thanks for the suggestions! I think most of this should be possible already.

If you have a look at the table page there is a toolbar with a set of buttons for working with the table. One of these that looks like a grid of squares lets you add/remove columns from the table. Whichever columns are currently visible will be included in any downloaded files.

![image](https://user-images.githubusercontent.com/6869320/80183621-712fb100-8609-11ea-81cf-be31be9881b6.png)

Selecting the "Added", "Updated" and "Pub Dates" columns should give you what you want.

We record the date for publications but not for preprints as they can be updated and it's not always clear which date is best to use. You can also see these dates on the tools page, here is an example for ACTINN

![image](https://user-images.githubusercontent.com/6869320/80183859-e307fa80-8609-11ea-9621-1d5e692f443e.png)

Hope that is what you were looking for and please let us know if you have any other suggestions

**Comment by lazappi** [comment]
Hi @ColeWunderlich 

I'm going to close this issue now. I hope that answered your question but if not please feel free to comment here.
